export default function Keyboard(){
        const keyboard = [
        { letter: 'Q' },
        { letter: 'W' },
        { letter: 'E' },
        { letter: 'R' },
        { letter: 'T' },
        { letter: 'Y' },
        { letter: 'U' },
        { letter: 'I' },
        { letter: 'O' },
        { letter: 'P' },
        { letter: 'S' },
        { letter: 'D' },
        { letter: 'F' },
        { letter: 'G' },
        { letter: 'H' },
        { letter: 'J' },
        { letter: 'K' },
        { letter: 'L' },
        { letter: 'Z' },
        { letter: 'X' },
        { letter: 'C' },
        { letter: 'V' },
        { letter: 'B' },
        { letter: 'N' },
        { letter: 'M' },
    ]
    return(<span></span>)
};